// AUTO-GENERATED demo dataset (mirrors the server seed) for the static/Pages build.
// Do not edit by hand — regenerate from the seeded DB if the catalogue changes.
import type { Car } from '../types';

export const CARS: Car[] = [
  {
    "id": 1,
    "make": "Tesla",
    "model": "Model 3",
    "trim": "Long Range",
    "year": 2024,
    "price": 44990,
    "monthly_price": 419,
    "body_type": "Saloon",
    "fuel_type": "Electric",
    "transmission": "Automatic",
    "mileage": 0,
    "color": "Pearl White",
    "condition": "new",
    "seats": 5,
    "doors": 4,
    "engine": "Dual Motor",
    "power_bhp": 498,
    "zero_to_sixty": 4.2,
    "top_speed": 145,
    "economy_mpg": 0,
    "rating": 4.7,
    "review_count": 1284,
    "accent": "#c0392b",
    "description": "The Tesla Model 3 blends blistering performance with a class-leading electric range and a minimalist, tech-forward cabin centred on a 15-inch touchscreen.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 2,
    "make": "BMW",
    "model": "3 Series",
    "trim": "320i M Sport",
    "year": 2024,
    "price": 41200,
    "monthly_price": 389,
    "body_type": "Saloon",
    "fuel_type": "Petrol",
    "transmission": "Automatic",
    "mileage": 0,
    "color": "Portimao Blue",
    "condition": "new",
    "seats": 5,
    "doors": 4,
    "engine": "2.0L Turbo",
    "power_bhp": 181,
    "zero_to_sixty": 7.1,
    "top_speed": 149,
    "economy_mpg": 45.6,
    "rating": 4.6,
    "review_count": 573,
    "accent": "#2563eb",
    "description": "A benchmark sports saloon: sharp handling, a refined interior and BMW’s slick iDrive infotainment make the 3 Series the driver’s choice in its class.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 3,
    "make": "Audi",
    "model": "A4",
    "trim": "35 TFSI S line",
    "year": 2023,
    "price": 38750,
    "monthly_price": 359,
    "body_type": "Saloon",
    "fuel_type": "Petrol",
    "transmission": "Automatic",
    "mileage": 8200,
    "color": "Mythos Black",
    "condition": "used",
    "seats": 5,
    "doors": 4,
    "engine": "2.0L TFSI",
    "power_bhp": 148,
    "zero_to_sixty": 8.6,
    "top_speed": 130,
    "economy_mpg": 47.1,
    "rating": 4.5,
    "review_count": 642,
    "accent": "#334155",
    "description": "Understated and beautifully built, the Audi A4 offers a hushed cabin, quality materials and effortless motorway cruising.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 4,
    "make": "Volkswagen",
    "model": "Golf",
    "trim": "1.5 TSI Life",
    "year": 2024,
    "price": 28900,
    "monthly_price": 279,
    "body_type": "Hatchback",
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "mileage": 0,
    "color": "Moonstone Grey",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "1.5L TSI",
    "power_bhp": 129,
    "zero_to_sixty": 9.2,
    "top_speed": 130,
    "economy_mpg": 51.4,
    "rating": 4.5,
    "review_count": 987,
    "accent": "#0ea5e9",
    "description": "The all-rounder’s all-rounder. The VW Golf pairs a grown-up driving experience with a practical, high-quality interior.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 5,
    "make": "Ford",
    "model": "Puma",
    "trim": "1.0 EcoBoost ST-Line",
    "year": 2024,
    "price": 26495,
    "monthly_price": 249,
    "body_type": "SUV",
    "fuel_type": "Hybrid",
    "transmission": "Manual",
    "mileage": 0,
    "color": "Desert Island Blue",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "1.0L EcoBoost mHEV",
    "power_bhp": 123,
    "zero_to_sixty": 9.8,
    "top_speed": 119,
    "economy_mpg": 52.3,
    "rating": 4.6,
    "review_count": 731,
    "accent": "#0891b2",
    "description": "Fun to drive with a clever ‘MegaBox’ boot, the Ford Puma is one of the most engaging small SUVs you can buy.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 6,
    "make": "Kia",
    "model": "Sportage",
    "trim": "1.6 T-GDi GT-Line",
    "year": 2024,
    "price": 34195,
    "monthly_price": 319,
    "body_type": "SUV",
    "fuel_type": "Hybrid",
    "transmission": "Automatic",
    "mileage": 0,
    "color": "Cityscape Green",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "1.6L T-GDi HEV",
    "power_bhp": 226,
    "zero_to_sixty": 8,
    "top_speed": 120,
    "economy_mpg": 49.6,
    "rating": 4.6,
    "review_count": 512,
    "accent": "#16a34a",
    "description": "Bold styling, a spacious cabin and a lengthy 7-year warranty make the Kia Sportage a standout family SUV.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 7,
    "make": "Hyundai",
    "model": "Ioniq 5",
    "trim": "77.4 kWh Ultimate",
    "year": 2024,
    "price": 48745,
    "monthly_price": 449,
    "body_type": "SUV",
    "fuel_type": "Electric",
    "transmission": "Automatic",
    "mileage": 0,
    "color": "Cyber Grey",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "Single Motor",
    "power_bhp": 225,
    "zero_to_sixty": 7.4,
    "top_speed": 115,
    "economy_mpg": 0,
    "rating": 4.7,
    "review_count": 468,
    "accent": "#64748b",
    "description": "Retro-futuristic looks, ultra-fast 800V charging and a lounge-like interior put the Ioniq 5 at the top of the EV class.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 8,
    "make": "Toyota",
    "model": "Corolla",
    "trim": "1.8 Hybrid Icon",
    "year": 2023,
    "price": 27310,
    "monthly_price": 259,
    "body_type": "Hatchback",
    "fuel_type": "Hybrid",
    "transmission": "Automatic",
    "mileage": 12500,
    "color": "Silver",
    "condition": "used",
    "seats": 5,
    "doors": 5,
    "engine": "1.8L Hybrid",
    "power_bhp": 138,
    "zero_to_sixty": 9.1,
    "top_speed": 112,
    "economy_mpg": 62.8,
    "rating": 4.5,
    "review_count": 823,
    "accent": "#dc2626",
    "description": "Bulletproof reliability and superb fuel economy define the self-charging hybrid Toyota Corolla.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 9,
    "make": "Mercedes-Benz",
    "model": "A-Class",
    "trim": "A200 AMG Line",
    "year": 2024,
    "price": 36850,
    "monthly_price": 349,
    "body_type": "Hatchback",
    "fuel_type": "Petrol",
    "transmission": "Automatic",
    "mileage": 0,
    "color": "Polar White",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "1.3L Turbo",
    "power_bhp": 161,
    "zero_to_sixty": 8.2,
    "top_speed": 142,
    "economy_mpg": 47.9,
    "rating": 4.4,
    "review_count": 559,
    "accent": "#1e293b",
    "description": "A premium hatchback with the slick MBUX infotainment system and a cabin that feels a class above.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 10,
    "make": "Nissan",
    "model": "Qashqai",
    "trim": "1.3 DiG-T N-Connecta",
    "year": 2024,
    "price": 31035,
    "monthly_price": 289,
    "body_type": "SUV",
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "mileage": 0,
    "color": "Magnetic Blue",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "1.3L DiG-T mHEV",
    "power_bhp": 138,
    "zero_to_sixty": 9.5,
    "top_speed": 121,
    "economy_mpg": 44.1,
    "rating": 4.4,
    "review_count": 690,
    "accent": "#3b82f6",
    "description": "The car that invented the crossover keeps getting better — practical, comfortable and easy to live with.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 11,
    "make": "Audi",
    "model": "Q3",
    "trim": "35 TFSI Sport",
    "year": 2024,
    "price": 39900,
    "monthly_price": 379,
    "body_type": "SUV",
    "fuel_type": "Petrol",
    "transmission": "Automatic",
    "mileage": 0,
    "color": "Glacier White",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "1.5L TFSI",
    "power_bhp": 148,
    "zero_to_sixty": 9.3,
    "top_speed": 130,
    "economy_mpg": 41.5,
    "rating": 4.4,
    "review_count": 402,
    "accent": "#475569",
    "description": "A compact premium SUV with a flexible interior and Audi’s trademark build quality.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 12,
    "make": "Tesla",
    "model": "Model Y",
    "trim": "Long Range AWD",
    "year": 2024,
    "price": 52990,
    "monthly_price": 489,
    "body_type": "SUV",
    "fuel_type": "Electric",
    "transmission": "Automatic",
    "mileage": 0,
    "color": "Midnight Silver",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "Dual Motor",
    "power_bhp": 434,
    "zero_to_sixty": 5,
    "top_speed": 135,
    "economy_mpg": 0,
    "rating": 4.6,
    "review_count": 913,
    "accent": "#111827",
    "description": "The UK’s best-selling EV: huge space, long range and access to the Supercharger network.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 13,
    "make": "BMW",
    "model": "X3",
    "trim": "xDrive20i M Sport",
    "year": 2023,
    "price": 46200,
    "monthly_price": 439,
    "body_type": "SUV",
    "fuel_type": "Petrol",
    "transmission": "Automatic",
    "mileage": 15400,
    "color": "Phytonic Blue",
    "condition": "used",
    "seats": 5,
    "doors": 5,
    "engine": "2.0L Turbo",
    "power_bhp": 181,
    "zero_to_sixty": 8.3,
    "top_speed": 132,
    "economy_mpg": 37.2,
    "rating": 4.5,
    "review_count": 377,
    "accent": "#1d4ed8",
    "description": "A polished mid-size SUV that drives with genuine agility while carrying the family in comfort.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 14,
    "make": "Volkswagen",
    "model": "ID.3",
    "trim": "Pro Match",
    "year": 2024,
    "price": 37690,
    "monthly_price": 349,
    "body_type": "Hatchback",
    "fuel_type": "Electric",
    "transmission": "Automatic",
    "mileage": 0,
    "color": "Kings Red",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "Single Motor",
    "power_bhp": 201,
    "zero_to_sixty": 7.4,
    "top_speed": 99,
    "economy_mpg": 0,
    "rating": 4.3,
    "review_count": 421,
    "accent": "#e11d48",
    "description": "VW’s electric hatchback offers a roomy cabin and an easy, refined drive for everyday EV motoring.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 15,
    "make": "Skoda",
    "model": "Octavia",
    "trim": "1.5 TSI SE L",
    "year": 2024,
    "price": 29650,
    "monthly_price": 269,
    "body_type": "Estate",
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "mileage": 0,
    "color": "Race Blue",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "1.5L TSI",
    "power_bhp": 148,
    "zero_to_sixty": 8.5,
    "top_speed": 139,
    "economy_mpg": 50.4,
    "rating": 4.6,
    "review_count": 604,
    "accent": "#0d9488",
    "description": "Vast boot, clever ‘Simply Clever’ touches and terrific value — the Octavia Estate is the ultimate sensible buy.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 16,
    "make": "Ford",
    "model": "Focus",
    "trim": "1.0 EcoBoost Titanium",
    "year": 2023,
    "price": 24500,
    "monthly_price": 235,
    "body_type": "Hatchback",
    "fuel_type": "Petrol",
    "transmission": "Manual",
    "mileage": 18900,
    "color": "Frozen White",
    "condition": "used",
    "seats": 5,
    "doors": 5,
    "engine": "1.0L EcoBoost",
    "power_bhp": 123,
    "zero_to_sixty": 10,
    "top_speed": 124,
    "economy_mpg": 52.3,
    "rating": 4.5,
    "review_count": 712,
    "accent": "#0284c7",
    "description": "Still the best-handling family hatchback around, with a comfortable ride and punchy small engines.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 17,
    "make": "Mercedes-Benz",
    "model": "GLC",
    "trim": "GLC 300e AMG Line",
    "year": 2024,
    "price": 58400,
    "monthly_price": 549,
    "body_type": "SUV",
    "fuel_type": "Hybrid",
    "transmission": "Automatic",
    "mileage": 0,
    "color": "Obsidian Black",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "2.0L PHEV",
    "power_bhp": 309,
    "zero_to_sixty": 6.7,
    "top_speed": 135,
    "economy_mpg": 176,
    "rating": 4.5,
    "review_count": 288,
    "accent": "#0f172a",
    "description": "A plush plug-in hybrid SUV with a huge electric-only range and a sumptuous, tech-laden cabin.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 18,
    "make": "Kia",
    "model": "EV6",
    "trim": "GT-Line 77.4 kWh",
    "year": 2024,
    "price": 47245,
    "monthly_price": 439,
    "body_type": "SUV",
    "fuel_type": "Electric",
    "transmission": "Automatic",
    "mileage": 0,
    "color": "Yacht Blue",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "Single Motor",
    "power_bhp": 226,
    "zero_to_sixty": 7.3,
    "top_speed": 115,
    "economy_mpg": 0,
    "rating": 4.7,
    "review_count": 356,
    "accent": "#0369a1",
    "description": "Striking design, rapid charging and a spacious, high-quality interior make the EV6 a top electric family car.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 19,
    "make": "Toyota",
    "model": "Yaris",
    "trim": "1.5 Hybrid Design",
    "year": 2024,
    "price": 23100,
    "monthly_price": 219,
    "body_type": "Hatchback",
    "fuel_type": "Hybrid",
    "transmission": "Automatic",
    "mileage": 0,
    "color": "Scarlet Flare",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "1.5L Hybrid",
    "power_bhp": 114,
    "zero_to_sixty": 9.7,
    "top_speed": 108,
    "economy_mpg": 68.9,
    "rating": 4.5,
    "review_count": 498,
    "accent": "#ea580c",
    "description": "A frugal, city-friendly supermini hybrid that sips fuel and shrugs off traffic.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 20,
    "make": "Land Rover",
    "model": "Defender",
    "trim": "110 D250 SE",
    "year": 2023,
    "price": 68900,
    "monthly_price": 649,
    "body_type": "SUV",
    "fuel_type": "Diesel",
    "transmission": "Automatic",
    "mileage": 9800,
    "color": "Pangea Green",
    "condition": "used",
    "seats": 7,
    "doors": 5,
    "engine": "3.0L D250",
    "power_bhp": 246,
    "zero_to_sixty": 8.3,
    "top_speed": 117,
    "economy_mpg": 32.1,
    "rating": 4.6,
    "review_count": 264,
    "accent": "#15803d",
    "description": "An icon reborn: genuinely go-anywhere ability paired with a rugged yet refined modern cabin.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 21,
    "make": "Honda",
    "model": "Civic",
    "trim": "2.0 e:HEV Sport",
    "year": 2024,
    "price": 33995,
    "monthly_price": 319,
    "body_type": "Hatchback",
    "fuel_type": "Hybrid",
    "transmission": "Automatic",
    "mileage": 0,
    "color": "Premium Crystal Red",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "2.0L e:HEV",
    "power_bhp": 181,
    "zero_to_sixty": 7.8,
    "top_speed": 111,
    "economy_mpg": 56.5,
    "rating": 4.6,
    "review_count": 341,
    "accent": "#b91c1c",
    "description": "A grown-up, great-to-drive hybrid hatch with a slick interior and excellent real-world economy.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 22,
    "make": "Peugeot",
    "model": "3008",
    "trim": "1.2 Hybrid GT",
    "year": 2024,
    "price": 37450,
    "monthly_price": 355,
    "body_type": "SUV",
    "fuel_type": "Hybrid",
    "transmission": "Automatic",
    "mileage": 0,
    "color": "Okenite White",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "1.2L Hybrid",
    "power_bhp": 134,
    "zero_to_sixty": 10.2,
    "top_speed": 124,
    "economy_mpg": 55.4,
    "rating": 4.4,
    "review_count": 219,
    "accent": "#4f46e5",
    "description": "A style-led family SUV with a striking i-Cockpit dashboard and an upmarket, distinctive feel.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 23,
    "make": "Volvo",
    "model": "XC40",
    "trim": "B4 Plus Dark",
    "year": 2024,
    "price": 42350,
    "monthly_price": 399,
    "body_type": "SUV",
    "fuel_type": "Hybrid",
    "transmission": "Automatic",
    "mileage": 0,
    "color": "Fjord Blue",
    "condition": "new",
    "seats": 5,
    "doors": 5,
    "engine": "2.0L B4 mHEV",
    "power_bhp": 194,
    "zero_to_sixty": 8.4,
    "top_speed": 112,
    "economy_mpg": 42.8,
    "rating": 4.6,
    "review_count": 383,
    "accent": "#1e40af",
    "description": "Safe, stylish and beautifully finished, the XC40 is one of the most desirable compact premium SUVs.",
    "created_at": "2026-07-10 11:29:46"
  },
  {
    "id": 24,
    "make": "MINI",
    "model": "Cooper",
    "trim": "Cooper S Classic",
    "year": 2023,
    "price": 25900,
    "monthly_price": 245,
    "body_type": "Hatchback",
    "fuel_type": "Petrol",
    "transmission": "Automatic",
    "mileage": 14200,
    "color": "Chili Red",
    "condition": "used",
    "seats": 4,
    "doors": 3,
    "engine": "2.0L Turbo",
    "power_bhp": 176,
    "zero_to_sixty": 6.8,
    "top_speed": 146,
    "economy_mpg": 42.2,
    "rating": 4.4,
    "review_count": 456,
    "accent": "#dc2626",
    "description": "Go-kart handling and heaps of character make the MINI Cooper S the most fun you can have in a small car.",
    "created_at": "2026-07-10 11:29:46"
  }
];
